# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def testOK(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
  
  def test_testOK(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
  
  def test_testKO(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("654321")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#failure-popup p").text == "Utilisateur ou mot de passe incorrect!"
    self.driver.close()
  
  def test_testdeconnexionavecfonctionRUN(self):
    self.testOK()
    self.driver.find_element(By.ID, "link-analytics").click()
    self.driver.find_element(By.LINK_TEXT, "Déconnexion").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "success-popup")))
    self.driver.close()
  
  def test_testticket(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
    self.driver.find_element(By.ID, "link-support").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("ajout d\'un utilisateur ")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("retour d\'un utilisateur deja equipé")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "success-popup")))
    self.driver.close()
  
  def test_testtiketsupport(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
    self.driver.find_element(By.ID, "link-users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "username").send_keys("wil")
    self.driver.find_element(By.ID, "email").send_keys("wil@test.com")
    self.driver.find_element(By.ID, "password").send_keys("wil")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    WebDriverWait(self.driver, NaN).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#success-popup p")))
    self.driver.find_element(By.ID, "link-dashboard").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) p").text == "1"
    self.driver.close()
  
  def test_testutilisateurOK(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
    self.driver.find_element(By.ID, "link-users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "username").send_keys("wil")
    self.driver.find_element(By.ID, "email").send_keys("wil@test.com")
    self.driver.find_element(By.ID, "password").send_keys("wil")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    WebDriverWait(self.driver, NaN).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#success-popup p")))
    self.driver.close()
  
  def test_testutilisateurforeach(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
    self.driver.find_element(By.ID, "link-users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "username").click()
    self.vars["utilisateurs"] = self.driver.execute_script("return[      [\'wil\', \'wil@test.com\', \'wil\'],     [\'wil\', \'wil1@test.com\', \'wil\'],     [\'wil\', \'wil2@test.com\', \'wil\'],     [\'wil\', \'wil3@test.com\', \'wil\'],     [\'wil\', \'wil4@test.com\', \'wil\'],  ]")
    collection = self.vars["utilisateurs"]
    for entry in collection:
      self.vars["utilisateur"] = entry
      self.driver.find_element(By.ID, "username").send_keys("${utilisateur[0]}")
      self.driver.find_element(By.ID, "email").click()
      self.driver.find_element(By.ID, "email").send_keys("${utilisateur[1]}")
      self.driver.find_element(By.ID, "password").click()
      self.driver.find_element(By.ID, "password").send_keys("${utilisateur[2]}")
      self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
      self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "link-dashboard").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) p").text == "5"
    self.driver.close()
  
  def test_testutilisateuridentique(self):
    self.driver.get("http://localhost/Projet-de-Test-Fonctionnel/index.html")
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#success-popup p").text == "Bienvenue, admin!"
    self.driver.find_element(By.ID, "link-users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "username").send_keys("wil")
    self.driver.find_element(By.ID, "email").send_keys("wil@test.com")
    self.driver.find_element(By.ID, "password").send_keys("wil")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    WebDriverWait(self.driver, NaN).until(expected_conditions.visibility_of_element_located((By.ID, "success-popup")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("liw")
    self.driver.find_element(By.ID, "email").send_keys("wil@test.com")
    self.driver.find_element(By.ID, "password").send_keys("liw")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "failure-popup").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.ID, "failure-popup")))
    self.driver.close()
  
